### ISSUE TITLE
Keyguard must not overwrite existing keyId in storage

### ISSUE THREAD

**Issue by sisou** [nimiq/keyguard-next#112]
When storing a new key, the Keyguard must check that the keyId is not already in use. If in use, the keyId needs to be altered so that it does not overwrite an existing key anymore.

This will also likely have to be the case when importing an existing key (which would usually overwrite it). Because the Keyguard only has access to the encrypted key (usually) and it cannot be sure that the password used was the same, the Keyguard has no way of knowing if an imported key with the same keyId is in fact the same key as already exists (if the existing encrypted entropy is bit-equal with the new encrypted entropy - meaning the user has used the same password again - then it would be safe to overwrite the existing key entry).

**Comment by Bettelstab** [comment]
Any reasons besides cookie limitations to note use full public key instead? Privacy issues I guess?

**Comment by sisou** [comment]
Yes, we could easily use a longer keyId, which would reduce risk of collision. But for that the cookie is the limiting factor basically.

**Comment by Bettelstab** [comment]
Discussion outcome: Use full 32 bytes internally to avoid collisions, use unique short id for cookie

**Comment by Bettelstab** [comment]
After revisiting this issue, I suggest the following: 
  - Id should be an autoincremented index
  - Save `publicKey` as additional property of Keys
  - In `Keystore.put()`, check that the publicKey does not exist yet. Otherwise, replace the old Key.

Seems that right? What should happen again if the user imports a key with a different password? Replace it anyway?

**Comment by sisou** [comment]
@danimoh I think there was some usecase where knowing the ID of the key without knowing the DB was useful, right? Maybe in the WalletCollector?

**Comment by danimoh** [comment]
I don't know of any right now.
For ledgers it's interesting to know the walletId to check whether the correct ledger is connected but that's not relevant for the keyGuard.

**Comment by sisou** [comment]
But in that regard, the keyguard still needs to forward an

**Comment by Bettelstab** [comment]
Solved by #200 !
