### ISSUE TITLE
Agree on passphrase vs password and update code everywhere

### ISSUE THREAD

**Issue by sisou** [nimiq/keyguard-next#134]

**Comment by nibhar** [comment]
I was under the impression the issue was settled on 'passphrase'? If so, update the title so it is no longer a pending discussion.

**Comment by sisou** [comment]
I believe the argument from UX was that `password` is more common and doesn't confuse the user. I don't remember there having been a definite decision.

**Comment by sisou** [comment]
It **PASSWORD**
