### ISSUE TITLE
KeyguardClient Singleton

### ISSUE THREAD

**Issue by danimoh** [nimiq/keyguard-next#149]
Explore whether it makes sense to offer a `KeyguardClient.Instance` getter as a `KeyguardCient` default / singleton instance.

**Comment by Bettelstab** [comment]
I don't see a big advantage in offering that in the Client. It's only used in Accounts, which is quite short-living, so there is hardly the case where we have several KeyguardClient instances in use.

What I suggest instead is a method `static setEndpoint(endpoint: string)`, so we don't have to pass a possible config parameter in Accounts each time we instantiate a KeyguardClient.
