### ISSUE TITLE
Support vesting contracts, HTLCs

### ISSUE THREAD

**Issue by danimoh** [nimiq/keyguard-next#164]

**Comment by Bettelstab** [comment]
Anything left to do here in keyguard? Maybe not.

**Comment by sisou** [comment]
I think nothing except actually testing it if it does accept and correctly sign vesting and HTLCs.

**Comment by danimoh** [comment]
We might still want to adapt the UI to display what the extra data in the contract creation actually means.

Redeeming transactions from vesting contracts and HTLCs should be alright?

**Comment by sisou** [comment]
Vesting contracts can be used as senders, that has been tested.

For decoding extra data, I created a more specialized issue #286.
