### ISSUE TITLE
Add error handling for failed IndexedDB reads and writes

### ISSUE THREAD

**Issue by sisou** [nimiq/keyguard-next#184]
For example "Error: Quota exceeded" when storage is full.

**Comment by Bettelstab** [comment]
How do you think should we handle those errors?

**Comment by sisou** [comment]
I think it should throw and thus reject with a dedicated error type, so that the AccountsManager can track it and display the error screen for it, telling the user what happened and hopefully why.

Currently these errors are just handed through to the end-user, which is not helpful.

**Comment by Bettelstab** [comment]
My current plan is to look into the code of Dexie.js and reuse what is possible.

**Comment by Bettelstab** [comment]
Keyguard part solved by #194
