### ISSUE TITLE
Make sure content is loaded before showing page on reload

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/keyguard-next#196]
As the hash is not empty when user reloads site, the browser finds an element to target and hence doesn't show the loading screen.

To solve this, we could e.g. explicitly set some class `initialized` to the app div and always show loading if it is not present.

**Comment by sisou** [comment]
#207 added the `loading` class to the `<body>` on start-up, which gets removed when the view is ready. #209 improves this by centralizing the handling into the `TopLevelApi`.
