### ISSUE TITLE
Does reading from the cookie jar correctly work in the iframe?

### ISSUE THREAD

**Issue by danimoh** [nimiq/keyguard-next#212]
Has this been testing?
If I'm not mislead, by the current implementation it shouldn't be working.

The cookie jar is included in the several requests, which live in `/request/[request-name]`.
In the creation of the ios cookie in `CookieJar.fill`, no path is specified.
Thus, the path is automatically set to `/request/[request-name]` the first time the cookie is set.

It will then not be readable from `/request/iframe` and not be updateable from `/request/[another-request-name]`.

Thus, `Path=/` should be set in the cookie creation.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Scope_of_cookies

**Comment by Bettelstab** [comment]
I tested it and you're right. Will change it after merge of #206

**Comment by Bettelstab** [comment]
Solved by #221
