### ISSUE TITLE
Replace all CSS-inlined icons by SVG sprite

### ISSUE THREAD

**Issue by sisou** [nimiq/keyguard-next#214]

**Comment by Bettelstab** [comment]
Todo: Ask @julianbauer about it

**Comment by sisou** [comment]
Will become a SVG Sprite, nearly done in nimiq-style.

**Comment by sisou** [comment]
Nimiq Style [v0.5.0 adds SVG sprites](https://github.com/nimiq/nimiq-style/commit/1f8914e177e42173de29b31b5795f1189860bdd8).

**Comment by Bettelstab** [comment]
#223
