### ISSUE TITLE
Should displayed tx value include fee?

### ISSUE THREAD

**Issue by sisou** [nimiq/keyguard-next#329]
I find this strange: I send 1 NIM. Now it says in big numbers "1.01242". I would expect it to rather be "1 NIM \n plus 0.01242 NIM fee".

![screenshot_from_2019-05-12_17-06-34](https://user-images.githubusercontent.com/1828163/57588944-af2ce580-751c-11e9-800d-412f67f7f4a8.png)

**Comment by julianbauer** [comment]
@sisou let's definitely exclude the fee
