### ISSUE TITLE
What should happen on keyguard reload?

### ISSUE THREAD

**Issue by danimoh** [nimiq/keyguard-next#53]
Should the window get closed?
That would probably be the easiest as the keyguard looses the state it had before reload, e.g. for `create` the chosen identicon (private key) + passphrase and that is stuff that we don't want to persist in localstorage

**Comment by svub** [comment]
should be firing. I like the idea @sisou! Sounds like a clean and predictable solution.

**Comment by sisou** [comment]
I believe with the current redirect RPC method, the keyguard receives its parameters via the URL query fragment (`?q=...`). Thus if the keyguard only changes the URL hash fragment, it should be able to preserve the RPC parameters on page reload and be able to start the request again, including the correct callback URL when the request is finished (or canceled). Needs testing though.

**Comment by sisou** [comment]
Tested this with the sign-transaction request type, it works as described in my last comment.
