### ISSUE TITLE
Passphrase box as component

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/keyguard-next#74]
Including animations and element fade-in/-outs as designed.

Simple API with submit and cancel events, onPassphraseIncorrect, settings for color and button text, optional secondary option (skip or similar).

**Comment by sisou** [comment]
Implemented in 93cc0cf41628401a1ea1a71a3f8c995f903d7e0a, not yet merged to `master`.

**Comment by sisou** [comment]
Implemented via cec3a2b4fe4c72fa5d2ded950117c991862d9131 and 94b1ce57fd6eb282667170f823704a81d36c4963.
