### ISSUE TITLE
Enable back-buttons in create flow

### ISSUE THREAD

**Issue by sisou** [nimiq/keyguard-next#84]
The page-header back-buttons in the create flow should be made functional, including the first back-button, which should take the user back to the AccountManager's wallet-type selection page.

**Comment by Bettelstab** [comment]
Solved in #86, not merged yet

**Comment by Bettelstab** [comment]
First back button needs https://github.com/nimiq/rpc/tree/max/recoverOnHistoryBack to be merged.

**Comment by sisou** [comment]
RPC PR now pending: https://github.com/nimiq/rpc/pull/3
